name: Rust

on: [push, pull_request]

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
    - name: Build
      working-directory:  ../../projexts
      run: cargo build --verbose
    - name: Run tests
      working-directory: ../../projexts
      run: cargo test --verbose
